### ISSUE TITLE
Problem on large upload > 150 MB

### ISSUE THREAD

**Issue by vfricou** [SillyWhale/jirafeau#1]
- Image version (or commit ref) : latest (sha256:5156ddad6d4b3af29e8c50ea3796e4034887acb10e4326a5a6a27e7a468e8540)
- Docker Version : 18.03-1
- Docker-compose version (if used) : 1.21.2
- Operating system and version : Debian stretch (9)

## Common problems

- Have you mapped volumes ? Yes
- Have you correctly mapped ports ? Yes

## Description

Please provide here most possible detail on issue.  

Problem on upload files > 150 MB, environment configured to could upload files < 2GB. 

Bug referenced on application original repository : [Issue #101](https://gitlab.com/mojo42/Jirafeau/issues/101)

## Step to reproduce

(How one can reproduce the issue - this is very important)

```yaml
version: '3.6'

services:
  app:
    image: sillywhale/jirafeau:latest
    ports:
      - 8082:80
    environment:
      - SIZE_LIMIT=2G
    volumes:
      - /srv/docker/jirafeau/data/config.local.php:/Jirafeau/lib/config.local.php
      - /srv/docker/jirafeau/data/uploads:/jirafeau-data/
    restart: always

```

## Relevant logs and/or screenshots

```
==> /var/log/nginx/jirafeau_error.log <==
2018/10/15 12:47:20 [error] 19#19: *7 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.34.3.205, server: _, request: "POST /script.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/jirafeau_php7-fpm.sock", host: "git01.nimes.fr:8082", referrer: "http://git01.nimes.fr:8082/"
```
